blank_issues_enabled: false
contact_links:
  - name: Discussions
    url: https://github.com/crafter-station/open-screenstudio/discussions
    about: For general questions and community discussions
  - name: WhatsApp Community
    url: http://crafters.chat/
    about: Chat with the community in real-time
